# Generated by Django 4.0.5 on 2022-06-16 15:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('todo_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedTodo',
            fields=[
                ('task', models.CharField(max_length=255)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('completed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
